---
version: "3"

services:
  transfer:
    build: .
    container_name: transfer
    environment:
      - PROVIDER=local
      - BASEDIR=/data
      - LOG=/data/log.log
      - PURGE_DAYS=14
      - PURGE_INTERVAL=24
    volumes:
      - ./data:/data # Choose a folder and make sure it exists.
    ports:
      - 8080:8080
    restart: unless-stopped
